export const GET_DOCUMENTS = "GET_DOCUMENTS";
export const INSERT_DOCUMENT = "INSERT_DOCUMENT";
export const DELETE_DOCUMENT = "DELETE_DOCUMENT";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const MAIL_SENDING = "MAIL_SENDING";
export const MAIL_SENT = "MAIL_SENT";
export const RESET_FORM = "RESET_FORM";
export const MAIL_NOT_SENT = "MAIL_NOT_SENT";

export const GET_CURRENT_USER = "GET_CURRENT_USER"